apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: default
type: Opaque
stringData:
  DB_USER: admin
  DB_PASSWORD: SuperMotDePasse123
  DB_NAME: mydatabase

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: myapp
          image: hexagone-api:1.0
          imagePullPolicy: Never
          envFrom:
            - secretRef:
                name: app-secret
          ports:
            - containerPort: 3000