apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gc
  namespace: argocd
spec: 
  project: default
  source:
    repoURL: "https://github.com/karlelisee/gc-devops.git"
    targetRevision: main
    path: helm/gc-app
    helm:
      releaseName: gc-staging
  destination: 
      server: "https://kubernetes.default.svc"
      namespace: gc-staging
  syncPolicy:
    automated:
      enabled: true